USE ConexaoSaude
GO


INSERT		INTO SubCategoriaCid
SELECT		C.Id, RTRIM(LTRIM(S.SUBCAT)) AS CodSubCategoria, 
			RTRIM(LTRIM(SUBSTRING(RTRIM(LTRIM(DESCRABREV)), 6, LEN(RTRIM(LTRIM(DESCRABREV))) - 5)))
FROM		SubCategoriasCID S 
			INNER JOIN CategoriaCid C ON C.Codigo = SUBSTRING(RTRIM(LTRIM(S.SUBCAT)), 0, 4) 
ORDER BY	C.Id, S.subCAT
